name: "Bug report"
description: "Report a reproducible issue"
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for helping improve EmergencyStorage! Please share as much detail as you can.
  - type: input
    id: summary
    attributes:
      label: Summary
      description: What went wrong?
      placeholder: "Downloads fail when using --openstreetmap"
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      description: List the exact commands or steps that trigger the issue.
      placeholder: |
        1. ...
        2. ...
        3. ...
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      placeholder: "Data should sync without errors"
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Logs / screenshots
      description: Paste relevant logs or attach screenshots.
      render: shell
  - type: input
    id: environment
    attributes:
      label: Environment
      description: OS, hardware (e.g., Raspberry Pi model), and storage target.
      placeholder: "Raspberry Pi 5, Ubuntu 24.04, USB HDD"
    validations:
      required: true
