name: Automatic Resource Updates

on:
  schedule:
    # Run daily at 02:00 UTC (can be customized in config)
    - cron: '0 2 * * *'
  workflow_dispatch:  # Allow manual triggering
    inputs:
      resources:
        description: 'Specific resources to update (comma-separated: resource1,resource2,etc.) or leave empty for all enabled'
        required: false
        default: ''

permissions:
  contents: write

jobs:
  auto-update:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y rsync curl wget
      
      - name: Run automatic updates
        run: |
          if [ -n "${{ github.event.inputs.resources }}" ]; then
            # Convert comma-separated list to command-line flags
            RESOURCES="${{ github.event.inputs.resources }}"
            FLAGS=""
            IFS=',' read -ra ADDR <<< "$RESOURCES"
            for resource in "${ADDR[@]}"; do
              FLAGS="$FLAGS --${resource}"
            done
            python3 scripts/auto_update.py $FLAGS
          else
            # Update all enabled resources
            python3 scripts/auto_update.py
          fi
      
      - name: Check for changes
        id: check_changes
        run: |
          if git diff --quiet; then
            echo "changed=false" >> $GITHUB_OUTPUT
          else
            echo "changed=true" >> $GITHUB_OUTPUT
          fi
      
      - name: Commit and push changes
        if: steps.check_changes.outputs.changed == 'true'
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add .
          git commit -m "chore: Automatic resource update [automated]"
          git push
